services:
  - type: web
    name: portal-frontend
    env: static
    buildCommand: ./render-build.sh
    staticPublishPath: build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
